title: Angeliot
description: Information Architect

url: https://github.com/baramnemse
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: baramnemse
   facebook: baramnemse
   email: baramnemse@gmail.com

