title: Angeliot
description: Information Architect

url: https://baramnemse.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
plugins: [jekyll-youtube]
paginate: 5

navigation:
 - title: Home
   url: /index.html
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

social:
   github: baramnemse
   facebook: baramnemse
   email: baramnemse@gmail.com

google_analytics: "UA-124436462-1"
